src/Recruiting/RecruitingWeb/Models/ErrorViewModel.cs
namespace RecruitingWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Recruiting/RecruitingWeb/Controllers/CandidatesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RecruitingWeb.Controllers
{
    public class CandidatesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Recruiting/RecruitingWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RecruitingWeb.Models;
using System.Diagnostics;

namespace RecruitingWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Recruiting/RecruitingWeb/Controllers/JobsController.cs
using Infrastructure.Services;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Models;

namespace RecruitingWeb.Controllers
{
    public class JobsController : Controller
    {
        private readonly IJobService _jobService;
        public JobsController(IJobService jobService) 
        {

            _jobService = jobService;

        }
        public async Task<IActionResult> Index()
       
        {
            // 3 ways we can send data from controller/actionb method to view
            // 1. ViewBag
            // 2. ViewData

            // 3. *** Strongly Typed Model data *****
            ViewBag.PageTitle = "Showing Jobs";
            var jobs = await _jobService.GetAllJobs();
            return View(jobs);
        }
        public async Task<IActionResult> Details(int id) 
        { 
            var job = await _jobService.GetJobById(id);
            return View(job);


        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        // Saving the Job Infor
        public async Task<IActionResult>Create(JobRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _jobService.AddJob(model);
            return RedirectToAction("Index");
        }

    }
}

src/Recruiting/RecruitingWeb/Controllers/SubmissionsController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace RecruitingWeb.Controllers
{
    public class SubmissionsController : Controller
    {
        private readonly ISubmissionsService _submissionsService;
        public SubmissionsController(ISubmissionsService submissionsService)
        {

            _submissionsService = submissionsService;

        }
        [HttpGet]
        public IActionResult Create(int id)
        {
            //var job = _submissionsService.GetJobById(id);

            //var model = new SubmissionsRequestModel
            //{
            //    JobId = job.Id,
            //    JobCode = job.JobCode,
            //    Title = job.Title
            //};
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>Create(SubmissionsRequestModel model,int id)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            int jobId = id;
            await _submissionsService.AddCandidate(model, jobId);
            return Redirect("/Jobs/Index");

        }
    }
}

src/Recruiting/RecruitingWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Recruiting/RecruitingWeb/Views/Jobs/Create.cshtml
@model ApplicationCore.Models.JobRequestModel

@{
    ViewData["Title"] = "Create";
    
}

<h1>Create</h1>

<h4>JobRequestModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPostions" class="control-label"></label>
                <input asp-for="NumberOfPostions" class="form-control" />
                <span asp-validation-for="NumberOfPostions" class="text-danger"></span>
            </div>
            <div class="form-group">
              <label asp-for="JobStatusLookUpId" class="control-label"></label>
              <select asp-for="JobStatusLookUpId" class="form-control">
                <option value="">Select an option</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
              <span asp-validation-for="JobStatusLookUpId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Recruiting/RecruitingWeb/Views/Jobs/Details.cshtml
@model ApplicationCore.Models.JobDetails

@{
    ViewData["Title"] = "Details";

}

<h1>Details</h1>

<div>
    <h4>JobDetails</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfPositions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfPositions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt>
            <button>
                <a asp-controller="Submissions" asp-action="Create" asp-route-id="@Model.Id">Apply</a>
            </button>
        </dt>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

src/Recruiting/RecruitingWeb/Views/Jobs/Index.cshtml
@model IEnumerable<ApplicationCore.Models.JobResponseModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="Jobs">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfPositions)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                 <a asp-controller="Jobs" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfPositions)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Id  }) 
            </td>
        </tr>
}
    </tbody>
</table>

src/Recruiting/RecruitingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecruitingWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecruitingWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RecruitingWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RecruitingWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Recruiting/RecruitingWeb/Views/Submissions/Create.cshtml
@model ApplicationCore.Models.SubmissionsRequestModel
@{
    ViewData["Title"] = "Create";

    
}


<h1>Create</h1>

<h4>XXX</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>